#define LASER_Pin GPIO_PIN_13
#define LASER_GPIO_Port GPIOG
#define POWER_CONTROL1_Pin GPIO_PIN_2
#define POWER_CONTROL1_GPIO_Port GPIOH
#define POWER_CONTROL2_Pin GPIO_PIN_3
#define POWER_CONTROL2_GPIO_Port GPIOH
#define POWER_COMTROL3_Pin GPIO_PIN_4
#define POWER_COMTROL3_GPIO_Port GPIOH
#define GREENLED8_Pin GPIO_PIN_8
#define GREENLED8_GPIO_Port GPIOG
#define POWER_CONTROL4_Pin GPIO_PIN_5
#define POWER_CONTROL4_GPIO_Port GPIOH
#define GREENLED7_Pin GPIO_PIN_7
#define GREENLED7_GPIO_Port GPIOG
#define GREENLED6_Pin GPIO_PIN_6
#define GREENLED6_GPIO_Port GPIOG
#define GREENLED5_Pin GPIO_PIN_5
#define GREENLED5_GPIO_Port GPIOG
#define GREENLED4_Pin GPIO_PIN_4
#define GREENLED4_GPIO_Port GPIOG
#define GREENLED3_Pin GPIO_PIN_3
#define GREENLED3_GPIO_Port GPIOG
#define GREENLED2_Pin GPIO_PIN_2
#define GREENLED2_GPIO_Port GPIOG
#define MPU6050_INT_Pin GPIO_PIN_1
#define MPU6050_INT_GPIO_Port GPIOC
#define GREENLED1_Pin GPIO_PIN_1
#define GREENLED1_GPIO_Port GPIOG
#define IIC_SCL_Pin GPIO_PIN_4
#define IIC_SCL_GPIO_Port GPIOA
#define IIC_SDA_Pin GPIO_PIN_5
#define IIC_SDA_GPIO_Port GPIOA
#define SINGLE_RED_Pin GPIO_PIN_11
#define SINGLE_RED_GPIO_Port GPIOE
#define SINGLEGREEN_Pin GPIO_PIN_14
#define SINGLEGREEN_GPIO_Port GPIOF
/* USER CODE BEGIN Private defines */
#define ONLINE 1
#define LOSSLINE 2
#define SAFTY_CONTROL 3
#define MANUAL_CONTROL 4
#define MPU_CONTROL 5
#define MOTO_CONTROL 6
#define MOCALUN_CONTROL 7



void task(void);
